[package]
name = "sufr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.13", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
pretty_assertions = "1.4.0"
substring = "1.4.5"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
